#server.port=8089
#
#spring.datasource.url=jdbc:h2:./db/movies review; AUTO_SERVER=true
#spring.datasource.username=root
#spring.datasource.password=123

server:
  port: 8089
spring:
  datasource:
    url: jdbc:h2:./db/movies review;AUTO_SERVER=true
    username: root
    password: 123
    driver-class-name: org.h2.Driver